# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=15)),
                ('patr', models.CharField(max_length=15)),
                ('sp', models.IntegerField()),
                ('np', models.IntegerField()),
                ('ph', models.IntegerField()),
            ],
        ),
    ]
