# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateConc', models.CharField(max_length=20)),
                ('expDate', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=15)),
                ('patr', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('square', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
